// Mock course data - temporary until we connect to Supabase
export const mockCourses = [
  {
    id: 1,
    title: "Basic geometry and measurement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim...",
    instructor: {
      name: "David Easdown",
      avatar: undefined,
    },
    duration: "1 hour",
    lessons: 30,
    level: "Advanced" as const,
    price: 10.99,
    originalPrice: 19.99,
    thumbnail: undefined,
  },
  {
    id: 2,
    title: "Introduction to Algebra",
    description: "Explore the foundations of algebra with clear explanations and practical examples.",
    instructor: {
      name: "Sarah Johnson",
      avatar: undefined,
    },
    duration: "2 hours",
    lessons: 25,
    level: "Intermediate" as const,
    price: 14.99,
    originalPrice: 29.99,
    thumbnail: undefined,
  },
  {
    id: 3,
    title: "Statistics Essentials",
    description: "Learn about data analysis, probability, and statistical concepts in a simple way.",
    instructor: {
      name: "Michael Smith",
      avatar: undefined,
    },
    duration: "1.5 hours",
    lessons: 20,
    level: "Beginner" as const,
    price: 12.49,
    originalPrice: 24.99,
    thumbnail: undefined,
  },
  {
    id: 4,
    title: "Calculus Fundamentals",
    description: "Dive into limits, derivatives, and integrals with comprehensive lectures and exercises.",
    instructor: {
      name: "Emily Chen",
      avatar: undefined,
    },
    duration: "3 hours",
    lessons: 30,
    level: "Advanced" as const,
    price: 19.99,
    originalPrice: 39.99,
    thumbnail: undefined,
  },
  {
    id: 5,
    title: "Data Science with Python",
    description: "A hands-on course that introduces data analysis and visualization techniques using Python.",
    instructor: {
      name: "James Lee",
      avatar: undefined,
    },
    duration: "4 hours",
    lessons: 15,
    level: "Intermediate" as const,
    price: 22.99,
    originalPrice: 45.99,
    thumbnail: undefined,
  },
  {
    id: 6,
    title: "Web Development Basics",
    description: "Learn how to build responsive websites using HTML, CSS, and JavaScript from scratch.",
    instructor: {
      name: "Laura Martinez",
      avatar: undefined,
    },
    duration: "5 hours",
    lessons: 10,
    level: "Beginner" as const,
    price: 15.99,
    originalPrice: 29.99,
    thumbnail: undefined,
  },
]
